services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: 'postgres:15-alpine'
    working_dir: /src
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '7604:5432'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - {{databaseContainerName}}:/var/lib/postgresql/data

  fastify:
    container_name: ${WEBSERVER_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    volumes:
      - ./src:/src # Mount project directory for live updates
#      - /src/node_modules # Exclude node_modules to avoid conflicts
    command: /bin/sh -c "npm install && npm run dev"
    #    environment:
#      NODE_ENV: development
volumes:
    {{databaseContainerName}}:
      driver: local